/**:
  ros__parameters:
    port: 8765
    address: "0.0.0.0"
    tls: false
    certfile: ""
    keyfile: ""
    topic_whitelist: [
      '/multiscan/.*',
      '/tf.*',
      '/cardinal_perception/filtered_scan',
      '/cardinal_perception/map_cloud',
      '/cardinal_perception/tags_detections',
      '/cardinal_perception/traversibility_points',
      '/cardinal_perception/process_metrics',
      '/cardinal_perception/scan_cb_metrics',
      '/cardinal_perception/mapping_cb_metrics',
      '/robot_description'
    ]
    param_whitelist: ['.*']
    service_whitelist: ['.*']
    client_topic_whitelist: ['.*']
    min_qos_depth: 1
    max_qos_depth: 10
    num_threads: 0
    send_buffer_limit: 500000
    capabilities: [ clientPublish, parameters, parametersSubscribe, services, connectionGraph, assets ]
    include_hidden: false
    asset_uri_allowlist: ['^package://(?:\\w+/)*\\w+\\.(?:dae|fbx|glb|gltf|jpeg|jpg|mtl|obj|png|stl|tif|tiff|urdf|webp|xacro)$']
