/**:
  ros__parameters:

    map_frame_id: "map"         # global frame (contains tags)
    odom_frame_id: "odom"       # odometry frame
    base_frame_id: "base_link"  # robot frame

    scan_topic: "/multiscan/lidar_scan"
    imu_topic: "/multiscan/imu"

    use_tag_detections:  0                # 1: enable, 0: disable, -1: filtered only
    require_rebias_before_tf_pub: true    # wait until successful trajectory filter rebias before publishing map --> odom tf
    require_rebias_before_scan_pub: true  # wait until successful trajectory filter rebias before republishing scans

    metrics_pub_freq: 10.  # frequency for printing stats

    trajectory_filter:
      sampling_window_s: 1.5
      min_filter_window_s: 0.4
      thresh:
        avg_linear_error: 0.13
        avg_angular_error: 0.09
        max_linear_deviation: 0.04
        max_angular_deviation: 0.04

    dlo:
      debug:
        publish_scans: true
      adaptive_params:
        use: true           # whether or not keyframe params scale with "spaciousness"
        lpf_coeff: 0.95
      gravity_align: true   # enable/disable gravity alignment on startup
      keyframe:
        thresh_D: 1.    # distance threshold in meters for creating a new keyframe
        thresh_R: 30.   # rotation threshold in degrees for creating a new keyframe
        submap:
          knn: 10   # how many nearest-neightbor poses to extract when building a submap?
          kcv: 15   # convex hull
          kcc: 15   # concave hull
      initial_pose:
        use: true                         # start with the provided pose?
        position: [ 0., 0., 0. ]          # x, y, z
        orientation: [ 1., 0., 0., 0. ]   # w, x, y, z
      crop_filter:
        use: true                     # exclude points within the provided bounding box (in the base frame) from processing
        min: [ -0.405, -0.6, 0.0 ]   # min corner ^
        max: [ 0.735, 0.6, 0.959 ]   # max corner ^
      voxel_filter:
        scan:
          use: true   # voxelize each input scan?
          res: 0.04   # leaf size
        submap:
          use: true   # voxelize each submap?
          res: 0.1    # leaf size
        adaptive_leaf_size:
          range_coeff: 0.063    # https://www.desmos.com/3d/0eoickmszv
          stddev_coeff: 0.064
          offset: -0.29
          floor: 0.04
          ceil: 0.5
          precision: 0.01

      imu:
        use: true           # integrate imu data to hint GICP?
        use_orientation: true
        calib_time: 3       # calibration time
        buffer_size: 2000   # measurement buffer length
      gicp:
        min_num_points: 100   # minimum points required
        s2s:
          k_correspondences: 25
          max_correspondence_distance: 1.
          max_iterations: 64
          transformation_epsilon: 0.01
          euclidean_fitness_epsilon: 0.005
          ransac:
            iterations: 12
            outlier_rejection_thresh: 2.5
        s2m:
          k_correspondences: 40
          max_correspondence_distance: 0.25
          max_iterations: 64
          transformation_epsilon: 0.005
          euclidean_fitness_epsilon: 0.005
          ransac:
            iterations: 12
            outlier_rejection_thresh: 5.

      mapping:
        valid_range: 4.
        frustum_search_radius: 0.01
        delete_range_thresh: 0.1
